name: cashier
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  crypto: ^3.0.6
  easy_localization: ^3.0.7+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  introduction_screen: ^3.1.17
  json_annotation: ^4.9.0  # Add this - required for freezed
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  freezed: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5  # This should also be in dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/logo/