class EmployeeSettings {
  List<String> permissions = [
    "create check" ,
    "edit_items" ,
    "view_items" ,
    "create order" ,
    "view order" ,
    "edit order" ,
    "delete order" ,
    "create invoice" ,
    "view invoice" ,
    "edit invoice" ,
    "delete invoice" ,
    "create customer" ,
    "view customer" ,
    "edit customer" ,
    "delete customer" ,
    "create supplier" ,
    "view supplier" ,
    "edit supplier" ,
    "delete supplier" ,
    "create product" ,
    "view product" ,
    "edit product" ,
    "delete product" ,
    "create category" ,
    "view category" ,
    "edit category" ,
    "delete category" ,
    "create brand" ,
    "view brand" ,
    "edit brand" ,
    "delete brand" ,
    "create unit" ,
    "view unit" ,
    "edit unit" ,
    "delete unit" ,
    "create role" ,
    "view role" ,
    "edit role" ,
    "delete role" ,
    "create employee" ,
    "view employee" ,
    "edit employee" ,
    "delete employee" ,
    "create user" ,
    "view user" ,
    "edit user" ,
  ] ;
}